### ISSUE TITLE
Top of app is clipped after load in firefox

### ISSUE THREAD

**Issue by activescott** [forkdelta/forkdelta.github.io#102]
With the new design the top of forkdelta gets clipped sometimes in firefox. [Video of issue here](https://github.com/forkdelta/forkdelta.github.io/files/1754128/forkdelta-top-clipped-after-load.mov.zip). I'll work on investigating...

**Comment by activescott** [comment]
Appears to have started with 272653eb8e46f909e16789f37d55234a49f2f4cf ...

**Comment by Palabola** [comment]
Confirmed

**Comment by activescott** [comment]
@Palabola Thanks! I also determined it can be prevented with the below and this seems to test out on FF, Chrome, and Safari: 

```
#trades {
  overflow-x: hidden
}
```

I'll play around with both to see which one seems safest and push one within the hour...

**Comment by freeatnet** [comment]
The patch didn't quite fix it everywhere.
