### ISSUE TITLE
Adding 888 token

### ISSUE THREAD

**Issue by 888-Token** [forkdelta/forkdelta.github.io#108]
Request to add the 888 token to your Exchange

   1 The contract address.
Contract Address: 0x87d9bF506B434e9973cb0e6183DA7A50A16796b2

   2 A link to the token issuer's official website.
Website: https://888token.xyz

   3 A couple sentences for token description.
888 Lucky Charm Tokens | limited to 888M Tokens

   4 A link to an official page confirming the contract address.
https://etherdelta.com/#0x87d9bf506b434e9973cb0e6183da7a50a16796b2-ETH

   5 A link to a third-party review or discussion of the token, like an established ICO review blog.
https://etherdelta.com/#0x87d9bf506b434e9973cb0e6183da7a50a16796b2-ETH

Link to download a 28x28png icon logo:
https://raw.githubusercontent.com/888-Token/888Token/master/888icon.png

**Comment by freeatnet** [comment]
@888-Token Please file this on [tokenbase](https://github.com/forkdelta/tokenbase)
