### ISSUE TITLE
how can install forkdelta on ubuntu?

### ISSUE THREAD

**Issue by yunsite** [forkdelta/forkdelta.github.io#133]
I have git clone under /var/www/,
and ln -s forkdelta to /var/www/html.

I can get the web index , but without data and chart info.

**Comment by Ebonsignori** [comment]
A better place for this question would be the ForkDelta [discord](https://discord.gg/MPvAfMa) or [reddit](https://www.reddit.com/r/ForkDelta/). 

It sounds like you need to run the backend's docker containers. Follow the instructions in the [backend repo](https://github.com/forkdelta/backend-replacement).

**Comment by freeatnet** [comment]
Hey @yunsite! You will need to set up forkdelta to be accessible as localhost, e.g., at http://localhost:8080. Let us know if you continue experiencing this issue.

**Comment by yunsite** [comment]
I install to http://192.161.176.58/

I have follewed the instructions in the backend repo.
root@bts:/opt/forkdelta.github.io-backend/backend-replacement# docker-compose ps
                  Name                                Command               State            Ports
-----------------------------------------------------------------------------------------------------------
backendreplacement_contract_observer_1     python3 -m app.services.co ...   Exit 1
backendreplacement_etherdelta_observer_1   python3 -m app.services.et ...   Exit 1
backendreplacement_huey_consumer_1         huey_consumer.py app.servi ...   Up       8080/tcp
backendreplacement_postgres_1              docker-entrypoint.sh postgres    Up       5432/tcp
backendreplacement_redis_1                 docker-entrypoint.sh redis ...   Up       6379/tcp
backendreplacement_ticker_1                python3 -m app.services.ticker   Exit 1
backendreplacement_websocket_server_1      python3 -m app.services.we ...   Up       0.0.0.0:8080->8080/tcp

**Comment by yunsite** [comment]
and change /conig/main.json with:
"socketServer": "http://192.161.176.58",
