### ISSUE TITLE
Missing 7400 PXBRL?? Help please

### ISSUE THREAD

**Issue by ryeben7** [forkdelta/forkdelta.github.io#139]
I am missing 7400 PXBRL...
The two transactions were for (7400) 7200 and 200 PXBRL tokens which I wanted to withdraw from my Forkdelta account to my Nano ledger wallet. However the PXBRL tokens are no longer showing on Forkdelta, or showing on my Nano. I have been on Delta balances to check https://deltabalances.github.io/recent.html#0x4b8bd304366Da6A5bbA04c5BC192CEb412AC9A1F
I have also followed the transactions 0xb33874a3b41e77d2e3934821917ca31d785f2f775170abc3d60f90b35e876380 0xe6c0f9677f3cf9347eb4cb564a5c9c3888687c07ddc313276d6de48a9e4c8bbf
I traced the funds (attempted to) and they look to have been sent to: 0x4b8bd304366da6a5bba04c5bc192ceb412ac9a1f (which is my fork delta account)
it then went to the address 0xa4da7e3f5a4baf3712576fa1193b990f02e3ffe3 and then appears to go to 0x8d12a197cb00d4747a1fe03395095ce2a5cc6819 ???
Can anyone please help?? I did not sell these or believe I transferred these to the wrong address... I'm totally unsure what has happened here....

**Comment by freeatnet** [comment]
This is not a support channel.

**Comment by ryeben7** [comment]
So can you help me with pointing me in the direction of a support channel?? I am struggling to find any info and support!

Regards
Ryan
