### ISSUE TITLE
using different smart contract

### ISSUE THREAD

**Issue by poa-delta** [forkdelta/forkdelta.github.io#159]
Hello, I have created poa-delta for poa to native token exchange. I have deployed sokol testnet contract and can deposit and withdrawl tokens and poa. I am unable to perform any buys or sell orders though. What are the next steps needed to get these functions working properly? Thanks forkdelta team! 
Here is the respiratory: github.com/poa-delta

**Comment by freeatnet** [comment]
Hey there! Good to hear about ForkDelta's code helping bootstrap exchanges on other chains!

Could you describe the issue you are facing in a bit more detail, though?

**Comment by poa-delta** [comment]
Well, the orders are not being placed. Click submit order, sign message and nothing shows up on the order book. I believe I need to host my own api on my own server (which I am working on)unless there is a way around doing that. Thanks for the answer back!

**Comment by freeatnet** [comment]
@poa-delta Oh. You definitely need an own instance of the backend to use a different chain & contract. Sorry about that.
