### ISSUE TITLE
Add a New Token

### ISSUE THREAD

**Issue by WorldLot** [forkdelta/forkdelta.github.io#162]
BEAST TOKEN

Smart contract address:
0x4ea1771f6ae14dc51e5f3236afca5de34b2c8021

Token symbol: BEAST

Telegram group:    https://t.me/TheCryptoExperiement
 (You can see a great community here which believe in this project and are excited to start purchasing BEAST token in order to pay for the service I am going to provide,

**Issuer's official website:**

Created on minereum.com
can check on tokenservice.minereum.com

**Description:** BEAST token was created as an experiment to see if the crypto community can turn a worthless token into something of value. We ran no ICO or are asking for initial funding but creating a true UTILITY token with a 1 of a kind service which will allow investor to find the best industry analysis for a monthly fee.
You can see our roadmap and updated visions on the official crypto beast website where this service will be implemented:
http://cryptobeast.uk/index.php/2018/07/03/beast-token-update

I have a FB group which is very behind this idea:
https://www.facebook.com/groups/cryptobeast.uk/
So there are potentially users from the start which will start purchasing BEAST on fork delta for my service.

I WANT TO ADD THAT IT WAS ONE OF THE MEMBERS OF THE TELEGRAM GROUP WHO SUGGESTED FOR ME AND MY TEAM TO GO AND USE FORK DELTA, AS IT IS MUCH BETTER THAN ETHER DELTA IN HIS WORKS, HE CAN BE FOUND IN THE CHAT AND YOU CAN SPEAK TO ANYBODY IN THE CHAT TO DISCUSS THIS:)

Thank you and I look forward to hearing from you.
Edward 
Crypto Beast

**Comment by WorldLot** [comment]
Transaction ID
0x8e1da1708eb5d88f695f49359ae7ffbd29ce83ac84c758277c48ad5fdfe368ad

**Comment by freeatnet** [comment]
All token listing requests must be filed on [forkdelta/tokenbase](https://github.com/forkdelta/tokenbase). Thank you for understanding and we look forward to listing your token.

**Comment by WorldLot** [comment]
Hello Arseniy

Thank you for letting me know. I have tried multiple times to understand how to create the pull request, my community have tried to explain it and I asked on your telegram channel but I am so confused as to what to choose when I go there what should i select for base and what should i select for master?

And after this do I enter the same info I did before?

Apologies if I am being difficult but would really like your help here as my community is really looking forward to it getting listed now.


Kind Regards
Edward Shuvalov
Sent from Outlook<http://aka.ms/weboutlook>
________________________________
