### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by WorldLot** [forkdelta/forkdelta.github.io#165]
Hi there I am getting an error message (by travis bot) when making a pull request and nobody seems to be able to help. I really hope you can 
it says:
6:1       error    syntax error: could not find expected ':'

What does this mean?

**Comment by freeatnet** [comment]
Please see https://github.com/forkdelta/tokenbase/pull/1462#issuecomment-406862037.

**Comment by WorldLot** [comment]
Hi there
I have made the changes and this did not help.
Maybe I am missing something?
By root level what exactly do you mean? I have made the altercation here:
https://github.com/forkdelta/tokenbase/pull/1462/commits/5ebbb903ead8b7f774030292858a203c8c38e61d

Or do I do the altercation somewhere else>?
