### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by WorldLot** [forkdelta/forkdelta.github.io#166]
hey there
my issue was closed before I could reply
 it was issue no 165

I have made the changes but its till having this issue can you send me a direct link as to where I should edit the description because I have done so here:
https://github.com/forkdelta/tokenbase/pull/1462
& also here:
https://github.com/forkdelta/tokenbase/pull/1462/files

Maybe I am just doing it in the wrong place>?
I am not sure what you meant by "root level"

**Comment by freeatnet** [comment]
Your issue was closed because this is not the right place to discuss a tokenbase issue. Please use https://github.com/forkdelta/tokenbase/pull/1462 for that.
