### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by Maxxxel** [forkdelta/forkdelta.github.io#18]
Why isnt it possible to do an order <1 Tokens? like [BUY] 0.00022 Tokens?

**Comment by freeatnet** [comment]
@Maxxxel There's a 0.01 minimum. It's required to keep order book clean and protect takers from paying unreasonably high transaction fees. Let me know if you have any suggestions.

**Comment by Maxxxel** [comment]
So I can't buy 0.0002 tokens for like 1500 ETH/Token?

**Comment by Maxxxel** [comment]
@freeatnet

**Comment by freeatnet** [comment]
There is currently no 1500 ETH/Token tokens listed :)

I understand your frustration. At the moment, it's a limitation of the parent platform: we work with EtherDelta liquidity and contract; we'll revise the logic of it when we move to our own contract. Perhaps, it's worth filing a reminder issue of forkdelta/proposals.

**Comment by Maxxxel** [comment]
Now I understand. Thanks that was all I wanted. And no. You won't find this trade. It was mine weeks ago. Lost all my money because somehow I entered the EtH/Token in the Amount field. Till today I don't know how this happened because I have some xp. Anyway. Thanks for the information
