### ISSUE TITLE
Listing of the Developer Network Token (DVN)

### ISSUE THREAD

**Issue by Timsn2017** [forkdelta/forkdelta.github.io#24]
Hello from Germany,

that you again for the possibilties you offer the community with your project.
I would like to request the listing of the Developer Network Token (DVN). 

About the Project:
In current developer discussion forums (like Stackoverflow) there is a lot of hate speech, duplicate questions, people getting tired of answering the same questions again and again and so there are many unnecessary discussions instead of answering the question the topic was about. 
With our project we want to introduce a rewarding system for deferential and constructive conversations between developers. The DVN project develops a Q&A portal with an integrated DVN tip system. 

Application example: 
A questioner can set a DVN tip reward on his question. Whoever gives the best and detailed answer (determined by the questioner and the community) receives the tip. This leads to detailed answers and a constructive atmosphere with a smart and simple solution.

We are already listed on IDEX Exchange: https://idex.market/eth/dvn

Token Details (verified on EtherScan):
Name: Developer Network Token
Contract Address: 0x9b7593aae6b48d02668808c2dfbfc4bef35ef957
Decimals: 18 
Symbol: DVN
Short description: The DVN project develops a Q&A portal with an integrated DVN tip system, where deferential conversation leads to profit for everyone.

Website: https://dvn-token.net
Thanks in advance! Please contact me for any questions!

Best Regards,
Tim

**Comment by freeatnet** [comment]
Looks good @Timsn2017! #25 contains the listing details and will be merged as soon as another ForkDelta contributor reviews the listing. You should double-check them, too :)

**Comment by Timsn2017** [comment]
Hey @freeatnet, Thanks! Just checked the changed files and the contract address as well. Everything seems to be fine ;)
