### ISSUE TITLE
Add blockarray token! (ARY)

### ISSUE THREAD

**Issue by smh020** [forkdelta/forkdelta.github.io#28]
This is the site for blockarray
It drops today at 8 pm EST

https://blockarray.com/

Here is more information:

https://icobench.com/ico/blockarray

https://icodrops.com/block-array/

Thanks in advance!

**Comment by freeatnet** [comment]
@smh020 Do you have the contract address?

**Comment by freeatnet** [comment]
> Token Address: 0xa5F8fC0921880Cb7342368BD128eb8050442B1a1
> Token Symbol: ARY
> Decimals of Percision: 18

— https://medium.com/blockarray/how-to-buy-ary-tokens-with-metamask-b9ddcb34e4a2
