### ISSUE TITLE
Add HKN (Hacken) ERC20 Token

### ISSUE THREAD

**Issue by thomaswde** [forkdelta/forkdelta.github.io#30]
I'd do a pull request but I'm not too slick with GitHub, here's what's needed:

*+    { "addr": "0x9e6b2b11542f2bc52f3029077ace37e8fd838d7f", "name": “HKN”, "decimals": 8 }*

Thank you, anything we can do to support these great projects, both ForkDelta and Hacken!!

**Comment by freeatnet** [comment]
@thomaswde Thanks for the suggestion! Hacken token has been added.

**Comment by thomaswde** [comment]
@freeatnet thanks!!
