### ISSUE TITLE
cV token

### ISSUE THREAD

**Issue by smh020** [forkdelta/forkdelta.github.io#34]
please add carvertical token!

https://etherscan.io/token/0xda6cb58a0d0c01610a29c5a65c303e13e885887c

https://www.carvertical.com/token-model/

https://icobench.com/ico/carvertical

https://icodrops.com/carvertical/

**Comment by freeatnet** [comment]
Contract address confirmation: https://www.carvertical.com/blog/how-to-follow-cv-tokens/
