### ISSUE TITLE
Add Horse token to forkdelta

### ISSUE THREAD

**Issue by nisargypandya1410** [forkdelta/forkdelta.github.io#37]
Hi,

Would it be possible for you guys to add horse token?

Token Address: 0x5B0751713b2527d7f002c0c4e2a37e1219610A6B
Token Symbol: HORSE
Decimals: 18

Website: https://ethorse.com/

Description: 
The World’s first DAPP to bet on the price of Cryptocurrencies. 
Ethorse is an Ethereum Smart Contract based DApp for betting on the price of Cryptocurrencies and win from everyone who bets against you. Users bet on a coin/token that performs the best among all the other competing ones in a specific time period. Bets are placed and rewards are claimed using Metamask plugin for Chrome/Firefox or the Ethereum based Mist browser. Being completely secured by the blockchain, no one has control over the race or user funds once a contract is deployed and a race is announced.

Review from steemit: https://steemit.com/cryptocurrency/@o1o1o1o/ethorse-ico-a-review
Review from icobench: https://icobench.com/ico/ethorse
Review from concourseq: https://concourseq.io/Q/ETHORSE

**Comment by sagarvikani** [comment]
👍

**Comment by freeatnet** [comment]
Now, this is a great format of the request!

**Comment by freeatnet** [comment]
Listed in https://github.com/forkdelta/forkdelta.github.io/commit/bf126e04fb02acbfacab5821b5689678becc6971
