### ISSUE TITLE
Litecoin Red / LTCRED

### ISSUE THREAD

**Issue by walerikus** [forkdelta/forkdelta.github.io#40]
Hello ForkDelta team, 

I am a community member of Litecoin Red, here is the information about this token

Smart Contract: 0x059e3ead0a5675e4139c820d799e20be9c75bc3d
Etherscan https://etherscan.io/token/0x059e3ead0a5675e4139c820d799e20be9c75bc3d
Website https://litecoinred.com/
Twitter https://twitter.com/litecoinred
Bitcointalk https://bitcointalk.org/index.php?topic=2474976.0
Telegram https://t.me/litecoinred

EtherDelta trading https://etherdelta.com/#0x059e3ead0a5675e4139c820d799e20be9c75bc3d-ETH

**Comment by freeatnet** [comment]
Listed in https://github.com/forkdelta/forkdelta.github.io/commit/bf126e04fb02acbfacab5821b5689678becc6971
