### ISSUE TITLE
Please add ELF token

### ISSUE THREAD

**Issue by halcy0n9001** [forkdelta/forkdelta.github.io#46]
Contract Address : https://etherscan.io/address/0xbf2179859fc6d5bee9bf9158632dc51678a4100e
Symbol : ELF
Decimal Places : 18

Description : 

>ælf, is a decentralized self-evolving cloud computing network. To establish a Blockchain infrastructure for various commercial requirements, ælf provides a highly efficient multi-chain parallel-processing system with cross-chain communication and self-evolving governance. It brings three innovations namely scalable nodes on cluster of computers, resource isolation for smart contracts via “one chain to one smart contract” and voting through token holders.

>ELF tokens are used to pay resource fees in the system, such as deployment of smart contracts, operating and upgrading of systems (transaction fees, cross-chain data transfer fees). It also enables community to vote on major decisions, such as electing mining nodes, introducing new features to the system and other major decisions.

- https://aelf.io/

**Comment by freeatnet** [comment]
Listed in https://github.com/forkdelta/forkdelta.github.io/commit/bf126e04fb02acbfacab5821b5689678becc6971

**Comment by halcy0n9001** [comment]
Thank you!
