### ISSUE TITLE
Add Zilliqa (ZIL)

### ISSUE THREAD

**Issue by thomaswde** [forkdelta/forkdelta.github.io#48]
Here ya go, thanks!
+ { "addr": "0x05f4a42e251f2d52b8ed15e9fedaacfcef1fad27", "name": “ZIL”, "decimals": 12 }

Here's the contract:
https://etherscan.io/address/0x05f4a42e251f2d52b8ed15e9fedaacfcef1fad27#readContract

**Comment by freeatnet** [comment]
Listed in https://github.com/forkdelta/forkdelta.github.io/commit/bf126e04fb02acbfacab5821b5689678becc6971
