### ISSUE TITLE
Can't add buy or sell orders to Fork Delta order book

### ISSUE THREAD

**Issue by ShizzleNizzle** [forkdelta/forkdelta.github.io#59]
I only have four sell orders open. Can't add buy or sell order to order book for: https://forkdelta.github.io/#!/trade/SHNZ-ETH

**Comment by freeatnet** [comment]
Sorry for the delay. Are you still experiencing this issue?

**Comment by ShizzleNizzle** [comment]
Hi. Thanks for replying. I figured out what the issue was. I had 9 open orders on EtherDelta that I couldn’t cancel. So even though I had less than 5 orders for that Ethereum address on Fork Delta, I couldn’t add any new orders.

 

Created a new MEW address and used that and that works.

 

You can close this.

 

Thanks!
