### ISSUE TITLE
The sell orders for BAT don't seem at all correct

### ISSUE THREAD

**Issue by nottoseethesun** [forkdelta/forkdelta.github.io#68]
After the cheapest sell price, all the orders shown are 100 times more expensive.  In this case, EtherDelta seems to be showing the accurate data.

**Comment by freeatnet** [comment]
Looks about right now. If you are still experiencing this issue, could you post a screenshot?

**Comment by nottoseethesun** [comment]
It is better but still a lot of the 0.05 bat/eth sell orders; see screenshot.
![screenshot from 2018-02-19 03-28-47](https://user-images.githubusercontent.com/308863/36375720-43ea547c-1525-11e8-95a6-744dc4a0f548.png)

**Comment by JonathonDunford** [comment]
Are you sure this is inaccurate?

**Comment by nottoseethesun** [comment]
No, not sure it is inaccurate (hence, “seem” in title).


Sent from Yahoo Mail for iPhone


On Friday, February 23, 2018, 11:19 AM, BigBrother <notifications@github.com> wrote:


Are you sure this is inaccurate?
