### ISSUE TITLE
Volume tab is not updated correctly

### ISSUE THREAD

**Issue by remedcu** [forkdelta/forkdelta.github.io#69]
There is some problem with the volumes tab.

The coin I listed: https://forkdelta.github.io/#!/trade/LOVE-ETH

had a single trade today (yes, I know, it's very low, but that's not the issue here :D), but still it didn't showed up on the volumes tab.

Also there is no Bid and Offer values as well, even though there are bids and offers.

It still is in zero for all the value as shown below:

<img src="https://image.prntscr.com/image/xovtuGsaQqSu9IWkopJ0kA.png">

**Comment by JonathonDunford** [comment]
We're seeing bid/ask data now. The last trade was 4 days ago, so can't really test.

I'd guess this was just an issue that resolved itself after we picked up LOVE in the API.
