### ISSUE TITLE
Add Presearch (PRE) token to forkdelta 

### ISSUE THREAD

**Issue by jejopl** [forkdelta/forkdelta.github.io#71]
Name: Presearch
Symbol: PRE
Contract address: 0x88a3e4f35d64aad41a6d4030ac9afe4356cb84fa

Description: Presearch is an open, decentralized search engine that rewards community members with Presearch Tokens for their usage, contribution to, and promotion of the platform.

Telegram: https://t.me/presearch
Twitter: https://twitter.com/TeamPresearch
Facebook: https://facebook.com/presearch.io

**Comment by thprt** [comment]
+1

**Comment by EmCrypto74** [comment]
+1

**Comment by ndshoang** [comment]
+1

**Comment by nick4all** [comment]
+1

**Comment by crypto-bovine** [comment]
+1

**Comment by colga63768** [comment]
+1

**Comment by wingertt** [comment]
I really pray for it to be listed

**Comment by wingertt** [comment]
+1

**Comment by CreativelyCloudy** [comment]
+1

**Comment by JonathonDunford** [comment]
Please reply to my comment here and we can get it out sooner: https://github.com/forkdelta/tokenbase/pull/121

**Comment by txtechs** [comment]
+1

**Comment by Kamy5** [comment]
+1

**Comment by jellesmedts** [comment]
+1

**Comment by jkluv000** [comment]
+1

**Comment by TripleEnter** [comment]
+1

**Comment by g33kr4m** [comment]
+1

**Comment by larrismarco** [comment]
+1
