### ISSUE TITLE
Still unable to access forkdelta using BRAVE browser

### ISSUE THREAD

**Issue by Adexbafo** [forkdelta/forkdelta.github.io#79]
I got one of the comment or reply in my mail, but am still unable to access forkdelta.github.io using BRAVE browser. Please do something about this, because have tried all other browsers no hurdles, but am convinient  using BRAVE browser because of its security. Thanks 
Let me say am using SAMSUNG TAB

**Comment by remedcu** [comment]
You don't have to create multiple issues of the same issue mate.

I have posted an answer there, check if it works. Else add details to the same issue.

Link: https://github.com/forkdelta/forkdelta.github.io/issues/76#issuecomment-367396957
