### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by drewmo** [forkdelta/forkdelta.github.io#82]
For some reason I am unable to authenticate using my server. I get a 401 response from your websocket when trying to connect over this endpoint: `var ws = $websocket('wss://api.forkdelta.com/socket.io/?EIO=42&transport=websocket');` Although strangely enough if I am running a local dev environment using localhost it seems the server connects just fine.

**Comment by freeatnet** [comment]
@drewmo This question is probably better addressed on https://github.com/forkdelta/backend-replacement, however:

We do [filter requests](https://github.com/forkdelta/backend-replacement/blob/master/app/services/websocket_server.py#L26) by Origin header. This is done to curb scammers. If you think your project should be on the approved list, let us know in the issues, please.
