### ISSUE TITLE
Add TEFOOD FARM TO FORK FOOD TRACEABILITY SYSTEM LICENSE TOKEN

### ISSUE THREAD

**Issue by smh020** [forkdelta/forkdelta.github.io#91]
TEFOOD FARM TO FORK FOOD TRACEABILITY SYSTEM LICENSE TOKEN

https://ethplorer.io/address/0x940d73c91db9f82440702f6cc8323a8c60583777

**Comment by JonathonDunford** [comment]
https://www.reddit.com/r/ForkDelta/comments/7tntnz/how_to_get_an_erc20_token_listed_on_forkdelta/
