### ISSUE TITLE
Add TEFOOD FARM TO FORK FOOD TRACEABILITY SYSTEM LICENSE TOKEN

### ISSUE THREAD

**Issue by smh020** [forkdelta/forkdelta.github.io#96]
You will need to include the following information in the issue:

The contract address.
0x940d73c91db9f82440702f6cc8323a8c60583777
A link to the token issuer's official website.
https://www.te-food.com/
A couple sentences for token description.
A link to an official page confirming the contract address.
TE-FOOD is a farm-to-table traceability solution, covering all logistics and food quality activities and data management of the supply chain. It provides cost effective software and identification tools to make livestock and fresh food supply information transparent.
A link to a third-party review or discussion of the token, like an established ICO review blog.
https://etherscan.io/address/0x940d73c91db9f82440702f6cc8323a8c60583777#code

![2018-02-23 11_58_03-telegram 1](https://user-images.githubusercontent.com/15349123/36614237-dbfdb02e-1890-11e8-83ed-501d8cdf5031.png)

**Comment by freeatnet** [comment]
Please post your request in https://github.com/forkdelta/tokenbase. Thanks!
