### ISSUE TITLE
Add REMME token

### ISSUE THREAD

**Issue by smh020** [forkdelta/forkdelta.github.io#98]
You will need to include the following information in the issue:

The contract address.
0x83984d6142934bb535793a82adb0a46ef0f66b6d
A link to the token issuer's official website.
https://remme.io/
A couple sentences for token description.
No more passwords — no more break-ins. REMME implements foolproof user authentication to protect from cyber attacks while eliminating passwords.
A link to an official page confirming the contract address.
https://ethplorer.io/address/0x83984d6142934bb535793a82adb0a46ef0f66b6d
A link to a third-party review or discussion of the token, like an established ICO review blog.
https://icobench.com/ico/remme
https://icodrops.com/remme/

**Comment by freeatnet** [comment]
Please post your request in https://github.com/forkdelta/tokenbase. Thanks!
